# Generated by Django 4.0.3 on 2022-03-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iDent', '0002_category_company_product_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('main_place', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('numbers', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Новости')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='Новости', verbose_name='Фото')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Актуально')),
            ],
        ),
    ]
