# Generated by Django 4.0.3 on 2022-03-18 13:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('iDent', '0003_address_contact_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='numbers',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KG', verbose_name=255),
        ),
    ]
