# Generated by Django 4.0.3 on 2022-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iDent', '0004_alter_contact_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
