# Generated by Django 4.0.3 on 2022-03-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iDent', '0005_main_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('text', models.TextField(max_length=255, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
