# Generated by Django 4.0.3 on 2022-03-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iDent', '0009_icons_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=255, verbose_name='Текст')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='icons',
            name='image',
            field=models.FileField(default='', upload_to='', verbose_name='Фото'),
        ),
    ]
