# Generated by Django 4.0.3 on 2022-03-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iDent', '0010_pictures_alter_icons_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('url', models.URLField(verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='main',
            name='text',
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='text',
        ),
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='main',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='swipers',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
