# Generated by Django 4.0.3 on 2022-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iDent', '0012_splitted_alter_category_title_alter_company_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('text', models.TextField(max_length=50, verbose_name='Заголовок')),
                ('image', models.FileField(default='', upload_to='', verbose_name='Значки')),
            ],
        ),
        migrations.AlterField(
            model_name='splitted',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото'),
        ),
    ]
